// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundTypeChatTheme;

impl BackgroundTypeChatTheme {
    /// This function creates an empty struct for the object BackgroundTypeChatTheme.
    pub fn new(theme_name: String) -> Self {
        Self { theme_name }
    }
}
