// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundFillFreeformGradient;

impl BackgroundFillFreeformGradient {
    /// This function creates an empty struct for the object BackgroundFillFreeformGradient.
    pub fn new(colors: Vec<i64>) -> Self {
        Self { colors }
    }
}
