// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundFillSolid;

impl BackgroundFillSolid {
    /// This function creates an empty struct for the object BackgroundFillSolid.
    pub fn new(color: i64) -> Self {
        Self { color }
    }
}
