// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundFill;
use crate::types::BackgroundTypePattern;
use crate::types::Document;

impl BackgroundTypePattern {
    /// This function creates an empty struct for the object BackgroundTypePattern.
    pub fn new(document: Document, fill: BackgroundFill, intensity: i64) -> Self {
        Self {
            document,
            fill,
            intensity,
            is_inverted: None,
            is_moving: None,
        }
    }
}
