// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundTypeWallpaper;
use crate::types::Document;

impl BackgroundTypeWallpaper {
    /// This function creates an empty struct for the object BackgroundTypeWallpaper.
    pub fn new(document: Document, dark_theme_dimming: i64) -> Self {
        Self {
            document,
            dark_theme_dimming,
            is_blurred: None,
            is_moving: None,
        }
    }
}
