// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundFill;
use crate::types::BackgroundTypeFill;

impl BackgroundTypeFill {
    /// This function creates an empty struct for the object BackgroundTypeFill.
    pub fn new(fill: BackgroundFill, dark_theme_dimming: i64) -> Self {
        Self {
            fill,
            dark_theme_dimming,
        }
    }
}
