// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::Birthdate;

impl Birthdate {
    /// This function creates an empty struct for the object Birthdate.
    pub fn new(day: i64, month: i64) -> Self {
        Self {
            day,
            month,
            year: None,
        }
    }
}
