// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BusinessOpeningHoursInterval;

impl BusinessOpeningHoursInterval {
    /// This function creates an empty struct for the object BusinessOpeningHoursInterval.
    pub fn new(opening_minute: i64, closing_minute: i64) -> Self {
        Self {
            opening_minute,
            closing_minute,
        }
    }
}
