// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BusinessOpeningHours;
use crate::types::BusinessOpeningHoursInterval;

impl BusinessOpeningHours {
    /// This function creates an empty struct for the object BusinessOpeningHours.
    pub fn new(time_zone_name: String, opening_hours: Vec<BusinessOpeningHoursInterval>) -> Self {
        Self {
            time_zone_name,
            opening_hours,
        }
    }
}
