// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BusinessConnection;
use crate::types::User;

impl BusinessConnection {
    /// This function creates an empty struct for the object BusinessConnection.
    pub fn new(
        id: String,
        user: User,
        user_chat_id: i64,
        date: i64,
        can_reply: bool,
        is_enabled: bool,
    ) -> Self {
        Self {
            id,
            user,
            user_chat_id,
            date,
            can_reply,
            is_enabled,
        }
    }
}
