// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BusinessIntro;

impl BusinessIntro {
    /// This function creates an empty struct for the object BusinessIntro.
    pub fn new() -> Self {
        Self {
            title: None,
            message: None,
            sticker: None,
        }
    }
}
