// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BusinessLocation;

impl BusinessLocation {
    /// This function creates an empty struct for the object BusinessLocation.
    pub fn new(address: String) -> Self {
        Self {
            address,
            location: None,
        }
    }
}
