// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::BackgroundType;
use crate::types::ChatBackground;

impl ChatBackground {
    /// This function creates an empty struct for the object ChatBackground.
    pub fn new(r#type: BackgroundType) -> Self {
        Self { r#type }
    }
}
