// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::InputPollOption;

impl InputPollOption {
    /// This function creates an empty struct for the object InputPollOption.
    pub fn new(text: String) -> Self {
        Self {
            text,
            text_parse_mode: None,
            text_entities: None,
        }
    }
}
