// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::Sticker;
use crate::types::StickerSet;

impl StickerSet {
    /// This function creates an empty struct for the object StickerSet.
    pub fn new(name: String, title: String, sticker_type: String, stickers: Vec<Sticker>) -> Self {
        Self {
            name,
            title,
            sticker_type,
            stickers,
            thumbnail: None,
        }
    }
}
