// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Document;
use serde::{Deserialize, Serialize};

/// The background is a wallpaper in the JPEG format.
/// <https://core.telegram.org/bots/api#backgroundtypewallpaper>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BackgroundTypeWallpaper {
    /// Document with the wallpaper
    pub document: Document,
    /// Dimming of the background in dark themes, as a percentage; 0-100
    pub dark_theme_dimming: i64,
    /// Optional. True, if the wallpaper is downscaled to fit in a 450x450 square and then box-blurred with radius 12
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_blurred: Option<bool>,
    /// Optional. True, if the background moves slightly when the device is tilted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_moving: Option<bool>,
}
