// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// The background is filled using the selected color.
/// <https://core.telegram.org/bots/api#backgroundfillsolid>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BackgroundFillSolid {
    /// The color of the background fill in the RGB24 format
    pub color: i64,
}
