// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// The background is taken directly from a built-in chat theme.
/// <https://core.telegram.org/bots/api#backgroundtypechattheme>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BackgroundTypeChatTheme {
    /// Name of the chat theme, which is usually an emoji
    pub theme_name: String,
}
