// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{BackgroundFillFreeformGradient, BackgroundFillGradient, BackgroundFillSolid};
use serde::{Deserialize, Serialize};

/// This object describes the way a background is filled based on the selected colors. Currently, it can be one of
/// - BackgroundFillSolid
/// - BackgroundFillGradient
/// - BackgroundFillFreeformGradient
/// <https://core.telegram.org/bots/api#backgroundfill>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "type")]
pub enum BackgroundFill {
    #[serde(rename = "solid")]
    BackgroundFillSolid(BackgroundFillSolid),
    #[serde(rename = "gradient")]
    BackgroundFillGradient(BackgroundFillGradient),
    #[serde(rename = "freeform_gradient")]
    BackgroundFillFreeformGradient(BackgroundFillFreeformGradient),
}
