// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Location;
use serde::{Deserialize, Serialize};

/// Contains information about the location of a Telegram Business account.
/// <https://core.telegram.org/bots/api#businesslocation>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BusinessLocation {
    /// Address of the business
    pub address: String,
    /// Optional. Location of the business
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<Location>,
}
