// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Chat;
use serde::{Deserialize, Serialize};

/// This object is received when messages are deleted from a connected business account.
/// <https://core.telegram.org/bots/api#businessmessagesdeleted>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BusinessMessagesDeleted {
    /// Unique identifier of the business connection
    pub business_connection_id: String,
    /// Information about a chat in the business account. The bot may not have access to the chat or the corresponding user.
    pub chat: Chat,
    /// The list of identifiers of deleted messages in the chat of the business account
    pub message_ids: Vec<i64>,
}
