// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::Sticker;
use serde::{Deserialize, Serialize};

/// <https://core.telegram.org/bots/api#businessintro>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BusinessIntro {
    /// Optional. Title text of the business intro
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Optional. Message text of the business intro
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Optional. Sticker of the business intro
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sticker: Option<Sticker>,
}
