// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BusinessOpeningHoursInterval;
use serde::{Deserialize, Serialize};

/// Describes the opening hours of a business.
/// <https://core.telegram.org/bots/api#businessopeninghours>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BusinessOpeningHours {
    /// Unique name of the time zone for which the opening hours are defined
    pub time_zone_name: String,
    /// List of time intervals describing business opening hours
    pub opening_hours: Vec<BusinessOpeningHoursInterval>,
}
