// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::BackgroundType;
use serde::{Deserialize, Serialize};

/// This object represents a chat background.
/// <https://core.telegram.org/bots/api#chatbackground>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ChatBackground {
    /// Type of the background
    pub r#type: BackgroundType,
}
