// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::MessageEntity;
use serde::{Deserialize, Serialize};

/// This object contains information about one answer option in a poll.
/// <https://core.telegram.org/bots/api#polloption>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PollOption {
    /// Option text, 1-100 characters
    pub text: String,
    /// Optional. Special entities that appear in the option text. Currently, only custom emoji entities are allowed in poll option texts
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text_entities: Option<Vec<MessageEntity>>,
    /// Number of users that voted for this option
    pub voter_count: i64,
}
