// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::SharedUser;
use serde::{Deserialize, Serialize};

/// This object contains information about the users whose identifiers were shared with the bot using a KeyboardButtonRequestUsers button.
/// <https://core.telegram.org/bots/api#usersshared>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UsersShared {
    /// Identifier of the request
    pub request_id: i64,
    /// Information about users shared with the bot.
    pub users: Vec<SharedUser>,
}
